data:
  # path to pickled bedroom
  data_path: /shared/data/new_room_data/bedroom_new_window_door_Img
  out_path:  tests/data/scene_outputs
  list_path: None

model:
  cat:
    start_token: 52
    stop_token: 51
    pad_token: 50
  # Todo: look up max_obj_num

  coor:
    start_token: 203
    stop_token: 202
    pad_token: 201


  orient:
    start_token: 363
    stop_token: 362
    pad_token: 361

  relation:
    start_token: 4
    stop_token: 3
    pad_token: 2

  dim:
    start_token: 83
    stop_token: 82
    pad_token: 81
    shape_cond: True


  max_seq_len: 80
  max_obj_num: 80
  cat_num: 28
  emb_dim: 128
  dim_fwd: 128
  num_heads: 4
  num_blocks: 8
  dropout: 0.3

train:
  aug:
    jitter_list: [0.,  0.05,  0.1,  0.15,  0.2, 0.25, 0.3]
    rotation_list: [0 , 30, 60,  90,120,150,   180,210, 240,  270]
  batch_size: 128
  epochs: 2000
  lr: 0.0003
  resume : null #lightning_logs/version_107/checkpoints/last.ckpt
  total_len: 1142
  train_len: 950
  l2: 0.001
  lr_restart: 10000
  warmup: 2000

test:
  num_samples: 2
  # sample outputs or choose deterministically?
  probabilistic: False
  model_file:  lightning_logs/version_226/checkpoints/last.ckpt
  log_dir: lightning_logs/version_20/out/